apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: puki121/project:1.0.0
          ports:
            - containerPort: 5000
