apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-namespace
spec:
  selector:
      app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer